# Generated by Django 3.2.12 on 2022-03-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, verbose_name='Ingredient Name')),
                ('kind', models.CharField(max_length=100, verbose_name='Kind')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Dish Name')),
                ('picture', models.URLField(verbose_name='Picture URL')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('ingredient', models.ManyToManyField(to='main.Ingredient')),
            ],
        ),
    ]
