# Generated by Django 3.2.12 on 2022-03-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seasoning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Seasoning Name')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='part',
            field=models.PositiveIntegerField(default=1, verbose_name='Part'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=400, verbose_name='Ingredient Name'),
        ),
    ]
