# Generated by Django 3.2.12 on 2022-03-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220312_1545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seasoning',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.PositiveIntegerField(blank=True, verbose_name='Price'),
        ),
    ]
