# Generated by Django 3.2.12 on 2022-03-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_ingredient_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.URLField(blank=True, verbose_name='Picture URL'),
        ),
    ]
